In [1]:
### numpy-play with (arrays)numbers
###pandas-dataset
###seaborn-data visualization
###matplotlib-data visualization
###scripy-statistical
###sklearn-algorithm


# numpy package for multidimensional

In [2]:
import numpy as np

In [3]:
list=[2,4,6]
np.array(list)

array([2, 4, 6])

In [4]:
list1=[[2,4,6],[2,5,7],[3,7,9]]
np.array(list1)

array([[2, 4, 6],
       [2, 5, 7],
       [3, 7, 9]])

In [6]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
np.arange(1,37,6)

array([ 1,  7, 13, 19, 25, 31])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [14]:
np.eye(10,dtype=int)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
print(np.random.randint(0,100))

68


In [16]:
array=np.random.randint(1,20,50)
array

array([ 1,  2, 19, 11, 15, 14, 12,  8,  3, 18, 15,  6,  8, 17,  6,  2,  6,
       17, 10,  5, 12, 11, 14, 11,  2,  7, 17,  9, 16, 11, 11, 11,  6, 16,
        3,  5, 10, 13, 10,  6, 18,  1,  1,  5, 16,  8, 10, 12, 19,  6])

In [19]:
array.reshape(5,10)

array([[ 1,  2, 19, 11, 15, 14, 12,  8,  3, 18],
       [15,  6,  8, 17,  6,  2,  6, 17, 10,  5],
       [12, 11, 14, 11,  2,  7, 17,  9, 16, 11],
       [11, 11,  6, 16,  3,  5, 10, 13, 10,  6],
       [18,  1,  1,  5, 16,  8, 10, 12, 19,  6]])

In [20]:
array.max()

19

In [21]:
array.T


array([ 1,  2, 19, 11, 15, 14, 12,  8,  3, 18, 15,  6,  8, 17,  6,  2,  6,
       17, 10,  5, 12, 11, 14, 11,  2,  7, 17,  9, 16, 11, 11, 11,  6, 16,
        3,  5, 10, 13, 10,  6, 18,  1,  1,  5, 16,  8, 10, 12, 19,  6])

In [22]:
array.argmax()

2

In [27]:
array=np.random.randint(1,5,5)
array

array([1, 1, 2, 4, 1])

In [28]:
array[1:4]

array([1, 2, 4])

In [29]:
array[1:2]=10
array

array([ 1, 10,  2,  4,  1])

In [30]:
array[:]=20
array

array([20, 20, 20, 20, 20])