In [1]:
import numpy as np

In [4]:
a=np.random.rand(2,3)

In [5]:
a

array([[0.80102516, 0.23808525, 0.60427076],
       [0.14894857, 0.01340054, 0.68652972]])

In [6]:
a.T


array([[0.80102516, 0.14894857],
       [0.23808525, 0.01340054],
       [0.60427076, 0.68652972]])

In [8]:
array1=np.arange(10,21)
array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
array1.argmax()

10

In [10]:
matr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
matr1[1,2]

6

In [14]:
matr1[2,:]

array([7, 8, 9])

In [15]:
matr1[2]

array([7, 8, 9])

In [ ]:
matr1[:,(3,2)]

In [5]:
import numpy as np


In [6]:
array1=np.random.rand(3,4)
array1

array([[0.01299373, 0.57176938, 0.86830562, 0.64726787],
       [0.03431339, 0.30283049, 0.85672142, 0.5839915 ],
       [0.82820382, 0.15273537, 0.86378574, 0.75934099]])

In [7]:
np.round(array1,decimals=2)

array([[0.01, 0.57, 0.87, 0.65],
       [0.03, 0.3 , 0.86, 0.58],
       [0.83, 0.15, 0.86, 0.76]])

In [9]:
sport=np.array(['cric','fball','golf','kabaddi'])
np.unique(sport)

array(['cric', 'fball', 'golf', 'kabaddi'], dtype='<U7')

# pandas

In [10]:
import pandas as pd

In [16]:
sports=pd.Series([1,2,3,4],index=['cricket','football','bball','rugby'])
sports

cricket     1
football    2
bball       3
rugby       4
dtype: int64

In [13]:
sports[1]

'cricket'

In [17]:
sports1=pd.Series([1,2,3,4],index=['javelin','football','chess','ttennis'])
sports1

javelin     1
football    2
chess       3
ttennis     4
dtype: int64

In [18]:
sports+sports1

bball       NaN
chess       NaN
cricket     NaN
football    4.0
javelin     NaN
rugby       NaN
ttennis     NaN
dtype: float64

In [19]:
df1=pd.DataFrame(np.random.rand(4,3),index='A B C D'.split(),columns='M1 M2 M3'.split())
df1

M1        M2        M3
A  0.517322  0.891954  0.022470
B  0.019915  0.186102  0.529531
C  0.311843  0.213079  0.898966
D  0.924126  0.479286  0.510232

In [23]:
df1=np.round(df1,decimals=2)

In [24]:
df1['M1']

A    0.52
B    0.02
C    0.31
D    0.92
Name: M1, dtype: float64

In [25]:
df1['TOTAL']=df1['M1']+df1['M2']+df1['M3']
df1

M1    M2    M3  TOTAL
A  0.52  0.89  0.02   1.43
B  0.02  0.19  0.53   0.74
C  0.31  0.21  0.90   1.42
D  0.92  0.48  0.51   1.91

In [28]:
print('😍')

😍


In [30]:
df2={'id':[1,2,3,4],'name':['john','jonny','janardhan','pai'],'salary':[10000,2000,30000,35000]}
df3=pd.DataFrame(df2)
df3

id       name  salary
0   1       john   10000
1   2      jonny    2000
2   3  janardhan   30000
3   4        pai   35000

In [32]:
df3['name']

0         john
1        jonny
2    janardhan
3          pai
Name: name, dtype: object

In [33]:
df3=df3.drop('id',axis=1)
df3

name  salary
0       john   10000
1      jonny    2000
2  janardhan   30000
3        pai   35000